"""add doctor profile fields

Revision ID: 0692a05a4cc9
Revises: bb495d17450f
Create Date: 2026-09-20 08:37:29.281885

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0692a05a4cc9"
down_revision: str | Sequence[str] | None = "bb495d17450f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
