"""add phone_verified to patients

Revision ID: 0c0e320bf664
Revises: f32af7273354
Create Date: 2026-09-15 17:32:51.264347

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c0e320bf664"
down_revision: str | Sequence[str] | None = "f32af7273354"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("patients", sa.Column("phone_verified", sa.Boolean(), nullable=True))
    op.execute(
        "UPDATE patients SET phone_verified = false WHERE phone_verified IS NULL"
    )
    op.alter_column("patients", "phone_verified", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("patients", "phone_verified")
    # ### end Alembic commands ###
