"""add doctor kyc fields to users

Revision ID: 113bbcded874
Revises: 2548508f21b6
Create Date: 2026-09-16 13:29:40.882442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113bbcded874'
down_revision: Union[str, Sequence[str], None] = '2548508f21b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kyc_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('kyc_selfie_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('kyc_id_document_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('kyc_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('kyc_verified_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('kyc_reviewed_by_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kyc_reviewed_by_note')
    op.drop_column('users', 'kyc_verified_at')
    op.drop_column('users', 'kyc_verified')
    op.drop_column('users', 'kyc_id_document_url')
    op.drop_column('users', 'kyc_selfie_url')
    op.drop_column('users', 'kyc_status')
    # ### end Alembic commands ###
