"""add login OTP fields, remove phone_verified

Revision ID: 2548508f21b6
Revises: 2d0ebc3aa192
Create Date: 2026-09-16 13:06:20.585189

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "2548508f21b6"
down_revision: str | Sequence[str] | None = "2d0ebc3aa192"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
