"""add national_id and phone_number to users

Revision ID: 2684540ded7b
Revises: 113bbcded874
Create Date: 2026-09-17 15:11:24.283065

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2684540ded7b"
down_revision: str | Sequence[str] | None = "113bbcded874"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "facilities", sa.Column("ppb_registration_number", sa.String(), nullable=True)
    )
    op.create_index(
        op.f("ix_facilities_ppb_registration_number"),
        "facilities",
        ["ppb_registration_number"],
        unique=True,
    )
    op.add_column("users", sa.Column("national_id", sa.String(), nullable=True))
    op.add_column("users", sa.Column("phone_number", sa.String(), nullable=True))
    op.create_index(op.f("ix_users_national_id"), "users", ["national_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_national_id"), table_name="users")
    op.drop_column("users", "phone_number")
    op.drop_column("users", "national_id")
    op.drop_index(
        op.f("ix_facilities_ppb_registration_number"), table_name="facilities"
    )
    op.drop_column("facilities", "ppb_registration_number")
    # ### end Alembic commands ###
