"""add login OTP fields, remove phone_verified

Revision ID: 2d0ebc3aa192
Revises: b06ee9429208
Create Date: 2026-09-16 13:05:15.907981

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d0ebc3aa192"
down_revision: str | Sequence[str] | None = "b06ee9429208"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("login_otp_hash", sa.String(), nullable=True))
    op.add_column(
        "users", sa.Column("login_otp_expires_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "login_otp_expires_at")
    op.drop_column("users", "login_otp_hash")
    # ### end Alembic commands ###
