"""add reset and verification token columns to users

Revision ID: b06ee9429208
Revises: f1caf9cc3a20
Create Date: 2026-09-16 06:54:49.984886

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b06ee9429208"
down_revision: str | Sequence[str] | None = "f1caf9cc3a20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "patients", "phone_number", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "patients", "phone_number", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
