"""add source to drugs

Revision ID: bb495d17450f
Revises: 2684540ded7b
Create Date: 2026-09-19 05:52:44.073465

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "bb495d17450f"
down_revision: str | Sequence[str] | None = "2684540ded7b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
